Repository Calysto/metakernel, pull requests merged in 2022-08, with the labels that each got.

#250 Strip paste-bracketing control characters
  metakernel/replwrap.py
  metakernel/tests/test_replwrap.py
Labels: bug

#251 Automated Changelog Entry for 0.29.1 on main
  CHANGELOG.md
Labels: documentation

#252 Restore versions of metakernel-echo and metakernel-python
  metakernel_echo/metakernel_echo.py
  metakernel_python/metakernel_python.py
Labels: bug

#254 Switch to hatch backend
  pyproject.toml
Labels: maintenance

#255 Automated Changelog Entry for 0.29.2 on main
  CHANGELOG.md
Labels: documentation

#256 Use hatch for example projects
  metakernel_echo/pyproject.toml
  metakernel_python/pyproject.toml
Labels: maintenance
